Update SageMaker inference example
localstack/localstack-pro-samples pull request #208
Opened 2023-02-27 10:12 UTC by silv-io

2023-02-27 13:23 UTC, HarshCasper requested changes
Hi — I continue to run into the following issue:

```sh
$ python3 main.py
Creating bucket...
Uploading model data to bucket...
Creating model in SageMaker...
Traceback (most recent call last):
  File "/Users/harshcasper/code/localstack/localstack-pro-samples/sagemaker-inference/main.py", line 133, in <module>
    run_regular()
  File "/Users/harshcasper/code/localstack/localstack-pro-samples/sagemaker-inference/main.py", line 117, in run_regular
    deploy_model(test_run)
  File "/Users/harshcasper/code/localstack/localstack-pro-samples/sagemaker-inference/main.py", line 38, in deploy_model
    sagemaker.create_model(ModelName=f"{MODEL_NAME}-{run_id}", ExecutionRoleArn=EXECUTION_ROLE_ARN,
  File "/Users/harshcasper/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/harshcasper/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the CreateModel operation (reached max retries: 4): exception while calling sagemaker.CreateModel: cannot import name 'sagemaker_stores' from 'localstack_ext.services.sagemaker.persistence' (/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/sagemaker/persistence.py)
```

2023-02-28 08:44 UTC, silv-io commented
> Hi — I continue to run into the following issue:
> 
> ```shell
> $ python3 main.py
> Creating bucket...
> Uploading model data to bucket...
> Creating model in SageMaker...
> Traceback (most recent call last):
>   File "/Users/harshcasper/code/localstack/localstack-pro-samples/sagemaker-inference/main.py", line 133, in <module>
>     run_regular()
>   File "/Users/harshcasper/code/localstack/localstack-pro-samples/sagemaker-inference/main.py", line 117, in run_regular
>     deploy_model(test_run)
>   File "/Users/harshcasper/code/localstack/localstack-pro-samples/sagemaker-inference/main.py", line 38, in deploy_model
>     sagemaker.create_model(ModelName=f"{MODEL_NAME}-{run_id}", ExecutionRoleArn=EXECUTION_ROLE_ARN,
>   File "/Users/harshcasper/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
>     return self._make_api_call(operation_name, kwargs)
>   File "/Users/harshcasper/.pyenv/versions/3.10.4/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
>     raise error_class(parsed_response, operation_name)
> botocore.exceptions.ClientError: An error occurred (InternalError) when calling the CreateModel operation (reached max retries: 4): exception while calling sagemaker.CreateModel: cannot import name 'sagemaker_stores' from 'localstack_ext.services.sagemaker.persistence' (/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/sagemaker/persistence.py)
> ```

Fixed it in https://github.com/localstack/localstack-ext/pull/1409

2023-03-02 13:51 UTC, silv-io commented
@HarshCasper this should work now

2023-03-02 15:40 UTC, HarshCasper approved these changes

2023-03-02 15:40 UTC, merged